### ISSUE TITLE
Texture maker error

### ISSUE THREAD

**Issue by renier-voigt** [jurialmunkey/script.texturemaker#2]
I’m running Kodi 20.2 on my AppleTV 4K (2nd Gen) and I’m using the Arctic Horizon 2 skin.

Every time I open Kodi, I get a notification on the top right saying “Texture Maker error” with the subtext “Check the log for more information.”

I’m not sure what exactly is causing this. 

I have noticed that when I go to settings and change the “colours” of the skin to anything besides “Skin Default” then it bugs out. You’re not able to see what you’ve currently got selected when it’s set to “Dark”,  “Darker” or any other colour. (I’m not sure if this is related to the error)

Photo of the error message: https://ibb.co/rFPVDvK

The log file: https://paste.kodi.tv/ihecojiwig

**Comment by Ade-AV** [comment]
Getting the same error after a Kodi crash, were you able to resolve?

**Comment by renier-voigt** [comment]
> Getting the same error after a Kodi crash, were you able to resolve?

Nope. I still get the same error message every time I open Kodi.

**Comment by ashbruh** [comment]
I also get the same error. I’m running Kodi on iPad so it seems it may be related to apple devices.

**Comment by jurialmunkey** [comment]
This is not something I can fix. 
The problem is the PIL module which is a dependency TextureMaker needs to run. 

Please report the issue on Kodi github otherwise it will never be fixed (and I can't report it myself as I don't own any iOS devices)
https://github.com/xbmc/xbmc/issues

**Comment by ashbruh** [comment]
Thanks for all your help then. Love the skin.

**Comment by tpaniaki** [comment]
@ashbruh Have you opened a ticket as jurial suggested? Could you please link it to this post?

**Comment by FrostByteLXV** [comment]
I've recently started getting this on my nVidia Shield.

- Arctic Fuse Skin 0.6.1
- Texture Maker 0.2.10
- kodi-20240318-40c09d0c-master-arm64-v8a.apk
- nVidia Shield

https://paste.kodi.tv/zenenifutu.kodi

**Comment by FrostByteLXV** [comment]
Opened Kodi issue just now

https://github.com/xbmc/xbmc/issues/24897

**Comment by FrostByteLXV** [comment]
If @jurialmunkey or anyone else wants to comment.  neo1973 believes it to be a skin issue.

Also, I'm not only getting this error whenever the skin loads, but I also get it whenever I go to and exit skin settings now.  v.0.6.2

https://github.com/xbmc/xbmc/issues/24897#issuecomment-2016946790

**Comment by jurialmunkey** [comment]
These are two different issues.

**Comment by jurialmunkey** [comment]
@FrostByteLXV it looks like your skin settings have become corrupted and somehow you've ended up with an icon saved as a colour.

Please reselect a colour scheme in appearance settings from skin settings to try to reset. Failing that, you can delete the skin.arctic.fuse folder from kodi/userdata/addon_data with kodi closed to reset the skin settings to defaults. This will only reset your skin settings not your widget config which is stored in skin variables folder.

**Comment by FrostByteLXV** [comment]
@jurialmunkey First, apologies for my confusion.  I was directed here from someone in the forum saying it was the same issue, but with the previous logs being expired I had no way of confirming.  I should have waited for your response though.
Resetting the color scheme worked.  Thanks.

**Comment by FrostByteLXV** [comment]
Someone else will have to open an issue then.  I don't have an iOS device either.

**Comment by jurialmunkey** [comment]
> @jurialmunkey First, apologies for my confusion. I was directed here from someone in the forum saying it was the same issue, but with the previous logs being expired I had no way of confirming. I should have waited for your response though. Resetting the color scheme worked. Thanks.

No worries.

It was an unusual error which I'm not quite sure how it would've happened in the first place. I did notice I made a small typo in the command in AF which I just fixed https://github.com/jurialmunkey/skin.arctic.fuse/commit/92386798d9098cc9a19005b151e5ea8ac13b9ffd but I don't think that would cause this issue -- I'm really not sure how you ended up with an icon saved in your color setting.

**Comment by FrostByteLXV** [comment]
Actually, now that I know the fix I'm pretty sure I know when it happened.  After one of the recent updates all my highlight colors (when you select an item) disappeared and all I saw was the text in bold when I selected something.  So, I went and changed "Customize highlight color" only at that time.   How all that caused an icon being in color setting I don't know.  

Anyhow, appreciate you taking the time to explain it.  Everyone on Emby who uses the Kodi addon asks what skin I'm using.

**Comment by Dextrik** [comment]
Hi @jurialmunkey, I have this error on the latest version of TvOS and Kodi v21.2.
Is this bug fixable by you or should I report it to Kodi github?

```
2025-01-21 16:31:36.642 T:205458   error <general>: GetDirectory - Error getting plugin://script.texturemaker/

2025-01-21 16:31:14.122 T:205525   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: dlopen(/private/var/containers/Bundle/Application/A1A57D53-81B2-4A43-ADEF-43419610D383/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.so, 0x0002): tried: '/private/var/containers/Bundle/Application/A1A57D53-81B2-4A43-ADEF-43419610D383/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.so' (code signature invalid in <D0F5AA40-2616-37DE-9092-74194B2854F5> '/private/var/containers/Bundle/Application/A1A57D53-81B2-4A43-ADEF-43419610D383/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.so' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x000DC470, codeBlobSize=0x00006370)
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/97F389D6-2E85-40CF-84BB-3C0B13348879/Library/Caches/Kodi/addons/script.texturemaker/script.py", line 5, in <module>
                                                       from resources.lib.script import Script
                                                     File "/private/var/mobile/Containers/Data/Application/97F389D6-2E85-40CF-84BB-3C0B13348879/Library/Caches/Kodi/addons/script.texturemaker/resources/lib/script.py", line 11, in <module>
                                                       from PIL import Image, ImageChops
                                                     File "/private/var/containers/Bundle/Application/A1A57D53-81B2-4A43-ADEF-43419610D383/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/Image.py", line 114, in <module>
                                                       from . import _imaging as core
                                                   ImportError: dlopen(/private/var/containers/Bundle/Application/A1A57D53-81B2-4A43-ADEF-43419610D383/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.so, 0x0002): tried: '/private/var/containers/Bundle/Application/A1A57D53-81B2-4A43-ADEF-43419610D383/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.so' (code signature invalid in <D0F5AA40-2616-37DE-9092-74194B2854F5> '/private/var/containers/Bundle/Application/A1A57D53-81B2-4A43-ADEF-43419610D383/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.so' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x000DC470, codeBlobSize=0x00006370)
                                                   -->End of Python script error report<--
```

The debuglog can be found here: https://paste.kodi.tv/apusitekit

**Comment by jurialmunkey** [comment]
> I have this error on the latest version of TvOS and Kodi v21.2. Is this bug fixable by you or should I report it to Kodi github?
> 

This is an error in an external module (PIL) so I cannot fix it. The module needs to be fixed for TvOS

**Comment by Mr-7mdan** [comment]
> > I have this error on the latest version of TvOS and Kodi v21.2. Is this bug fixable by you or should I report it to Kodi github?
> 
> This is an error in an external module (PIL) so I cannot fix it. The module needs to be fixed for TvOS

But why it was working before? I also noticed that if i get AH2 through a build, it works fine. But if install the skin from the repo, it produces the texture maker error

**Comment by Mr-7mdan** [comment]
Btw, the texture maker error occurs for AH2 and AF2 but not AF3.
Platform: tvOS

**Comment by jurialmunkey** [comment]
> Btw, the texture maker error occurs for AH2 and AF2 but not AF3.

Texture maker is not used in AF3 to generate textures.
