### ISSUE TITLE
numpy update

### ISSUE THREAD

**Issue by s0ulslack** [jurialmunkey/script.texturemaker#3]
After upgrading to numpy-2 I've been getting the following error;
```

2024-07-30 00:22:24.069 T:25204   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: CPU dispatcher tracer already initlized
                                                   Traceback (most recent call last):
                                                     File "/home/soul/.kodi/addons/script.texturemaker/script.py", line 5, in <module>
                                                       from resources.lib.script import Script
                                                     File "/home/soul/.kodi/addons/script.texturemaker/resources/lib/script.py", line 11, in <module>
                                                       from PIL import Image, ImageChops
                                                     File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 68, in <module>
                                                       from ._typing import StrOrBytesPath, TypeGuard
                                                     File "/usr/lib/python3.12/site-packages/PIL/_typing.py", line 8, in <module>
                                                       import numpy.typing as npt
                                                     File "/usr/lib/python3.12/site-packages/numpy/__init__.py", line 114, in <module>
                                                       from numpy.__config__ import show as show_config
                                                     File "/usr/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module>
                                                       from numpy._core._multiarray_umath import (
                                                     File "/usr/lib/python3.12/site-packages/numpy/_core/__init__.py", line 23, in <module>
                                                       from . import multiarray
                                                     File "/usr/lib/python3.12/site-packages/numpy/_core/multiarray.py", line 10, in <module>
                                                       from . import overrides
                                                     File "/usr/lib/python3.12/site-packages/numpy/_core/overrides.py", line 8, in <module>
                                                       from numpy._core._multiarray_umath import (
                                                   RuntimeError: CPU dispatcher tracer already initlized
```

This looks semi related to the open bug but I wasn't sure?
Thank you!

**Comment by jurialmunkey** [comment]
This is not an error in the plugin. It is an error in an external module. I can't fix errors in external python modules.

You need to use the version of numpy which is comparable with the version of PIL on your system.

**Comment by s0ulslack** [comment]
I apologize for opening this then, thank you for the rely
